name = "Tram2DKF"
uuid = "32cd5d51-e88c-4eff-9d1b-565e2e4b205b"
authors = ["Jakub Vaněk <vanekj19@fel.cvut.cz>"]
version = "1.0.0-DEV"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Zygote = "e88e6eb3-aa80-5325-afca-941959d7151f"

[compat]
julia = "1.10"
